// <auto-generated />
namespace DVT.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial61));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191420228_initial61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
