// <auto-generated />
namespace DVT.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initials1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707041838454_initials1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
